In [152]:
import pandas as pd
import numpy as np
import scipy as sp

from numpy.testing import rundocs
import matplotlib.pyplot as plt
#import talib
import random
import sklearn
from sklearn import preprocessing
import tensorflow
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

#from datetime import strptime

ImportError: cannot import name 'strptime'

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
df = pd.read_excel(open('Cost.xls', 'rb'), sheet_name='Sheet1')
df.head(76)

In [ ]:
dataset = df.values

In [ ]:
dataset

In [ ]:
X = dataset[:,1:15]

In [ ]:
X

In [ ]:
Y = dataset[:,16]

In [ ]:
Y

In [ ]:
from sklearn import preprocessing

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [ ]:
X_scale

In [ ]:
min_max_scaler2 = preprocessing.MinMaxScaler()
#Y_scale = min_max_scaler2.fit_transform(Y)

In [ ]:
#Y_scale

In [ ]:
from sklearn.feature_extraction import DictVectorizer

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X, Y, test_size=0.3)
#X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)
#X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y_scale, test_size=0.3)

In [ ]:
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [ ]:
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

In [ ]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

In [ ]:
# define 10-fold cross validation test harness
#kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [ ]:
for train, test in kfold.split(X_scale, Y):
# create model
	model2 = Sequential()
	model2.add(Dense(12, input_dim=14, activation='relu'))
	model2.add(Dense(8, activation='relu'))
	model2.add(Dense(1, activation='sigmoid'))
	# Compile model
	model2.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
	# Fit the model
	model2.fit(X_scale[train], Y[train], epochs=150, batch_size=9, verbose=0)
	# evaluate the model
	scores = model2.evaluate(X_scale[train], Y[train], verbose=0)
	print("%s: %.2f%%" % (model2.metrics_names[1], scores[1]*100))
	cvscores.append(scores[1] * 100)
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

In [ ]:
cvscores2 = []
for train, test in kfold.split(X_train, Y_train):
# create model
    model3 = Sequential([
        Dense(6, activation='sigmoid', input_shape=(14,)),
        #    Dense(3, activation='sigmoid'),
        Dense(1, activation='sigmoid'),
    ])
    epochs=400
    learning_rate = 0.1
    decay_rate = learning_rate / epochs
    momentum = 0.8
    sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)
    model3.compile(optimizer='sgd',
              loss='mse',              
              metrics=['accuracy'])
    hist3 = model3.fit(X_train, Y_train,
          batch_size=9, epochs=epochs,
          validation_data=(X_val, Y_val))
    scores = model3.evaluate(X_scale[train], Y[train], verbose=0)
    cvscores2.append(scores[1] * 100)
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores2), np.std(cvscores)))    


In [ ]:
model3.evaluate(X_test, Y_test)[1]

In [ ]:
plt.plot(hist3.history['loss'])
plt.plot(hist3.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper right')
plt.show()

In [ ]:
model = Sequential([
    Dense(6, activation='sigmoid', input_shape=(14,)),
#    Dense(3, activation='sigmoid'),
    Dense(1, activation='sigmoid'),
])

In [ ]:
epochs=400
learning_rate = 0.1
decay_rate = learning_rate / epochs
momentum = 0.8
sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)
#model.compile(optimizer='sgd',
#              loss='binary_crossentropy',
#              metrics=['accuracy'])
#opt = model.optimizers.Adam(learning_rate=0.1)
#model.compile(optimizer='adam',
#model.compile(optimizer=opt,
model.compile(optimizer='sgd',
              loss='mse',              
              metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', optimizer='SGD', metrics=['accuracy'])

In [ ]:
hist = model.fit(X_train, Y_train,
          batch_size=9, epochs=epochs,
          validation_data=(X_val, Y_val))

In [ ]:
model.evaluate(X_test, Y_test)[1]

In [ ]:
plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper right')
plt.show()

In [ ]:
from keras.models import Sequential

In [ ]:
#model = Sequential()
weights = model.get_weights()

In [153]:
print(weights)

[array([[ 0.19229531,  0.35451013, -0.3189302 ,  0.03631765, -0.49259374,
         0.08184843],
       [-0.22001639,  0.27761948, -0.4241109 ,  0.15830255, -0.41002423,
        -0.4549794 ],
       [ 0.08516902,  0.09501839, -0.30762577,  0.14406699, -0.10735095,
        -0.08530804],
       [-0.00176865, -0.16515985,  0.17678303,  0.36890817, -0.38025868,
        -0.44199193],
       [ 0.42518395,  0.19149312, -0.24752177, -0.40831965, -0.49820352,
         0.3912526 ],
       [-0.41983053, -0.13782778,  0.06917561,  0.54590476, -0.05153587,
         0.42513534],
       [-0.10494292, -0.5430383 , -0.24095905, -0.08694434, -0.4670232 ,
         0.39805436],
       [-0.08974373,  0.34072328,  0.05154237,  0.31725687,  0.521268  ,
         0.2622502 ],
       [ 0.13293219,  0.52716446, -0.501592  ,  0.31634134,  0.10314888,
         0.07662079],
       [-0.54623413,  0.19757938,  0.08911473,  0.12227404, -0.03189397,
        -0.08992677],
       [ 0.32170767, -0.08097962, -0.04019903, -0

In [154]:
model.summary()

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_57 (Dense)             (None, 6)                 90        
_________________________________________________________________
dense_58 (Dense)             (None, 1)                 7         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [155]:
Xnew = [[2002, 1.9, 1], [2012, 2, 1], [2015, 2, 4]]
Xnew = [2002, 1.9, 1]
Xnew

[2002, 1.9, 1]

In [156]:
df_t = pd.read_excel(open('Cost.xls', 'rb'), sheet_name='Test1')
df_t.head()

Unit Name  Type Unit  Region  Lease/ Own  Water Depth\n(meters)  \
0                  1          1       2           1                    825   
1                  2          2       1           2                    600   
2               P 57          1       3           1                   1300   
3  Pioneiro de Libra          1       3           1                   2200   
4               P 63          1       3           2                   1170   

   Contracting Date  Contract (EPC, CL, PS, TK)  \
0              4096                           1   
1              3894                           1   
2              4796                           1   
3              7158                           4   
4              5387                           1   

   Local Content Requirment (H,M,A,L, N)  Technology Novelt (H,M,A,L,N)  \
0                                      3                              3   
1                                      2                              1   
2                                      5                              1   
3                                      5                              1   
4                                      5                              1   

   FEED Detail (H,M,A,L,N)  FEED Detail (H,M,A,L,N).1  Lessons Learned  \
0                        4                          4                2   
1                        4                          4                3   
2                        1                          1                4   
3                        1                          1                5   
4                        2                          2                2   

   Company (NOC, IOC, OC)  Planned_Duration  Planned_Cost  Schedule_Overrun  \
0                       2               702      0.598425         -0.143875   
1                       2               994      1.133000         -0.022133   
2                       1              1041      1.195000         -0.045149   
3                       1               831      1.000000          0.457280   
4                       1              1383      1.300000          0.086768   

   Cost_Overrun  
0      0.270000  
1      0.350000  
2      0.004184  
3      0.594411  
4      0.253846

In [157]:
dataset_t = df_t.values
Xnew = dataset_t[:,1:15]
Xnew


array([[1, 2, 1, 825, 4096, 1, 3, 3, 4, 4, 2, 2, 702, 0.5984251968503937],
       [2, 1, 2, 600, 3894, 1, 2, 1, 4, 4, 3, 2, 994, 1.133],
       [1, 3, 1, 1300, 4796, 1, 5, 1, 1, 1, 4, 1, 1041, 1.195],
       [1, 3, 1, 2200, 7158, 4, 5, 1, 1, 1, 5, 1, 831, 1.0],
       [1, 3, 2, 1170, 5387, 1, 5, 1, 2, 2, 2, 1, 1383, 1.3]],
      dtype=object)

In [158]:
ynew1 = model.predict(Xnew)

In [159]:
print("The values of Xnew and its predicted yhat")
for loop in range(len(Xnew)):
        print("Xnew[%s] = %s, ynew[%s] = %s " % (loop,Xnew[loop],loop,ynew1[loop]))

The values of Xnew and its predicted yhat
Xnew[0] = [1 2 1 825 4096 1 3 3 4 4 2 2 702 0.5984251968503937], ynew[0] = [0.3433653] 
Xnew[1] = [2 1 2 600 3894 1 2 1 4 4 3 2 994 1.133], ynew[1] = [0.3433653] 
Xnew[2] = [1 3 1 1300 4796 1 5 1 1 1 4 1 1041 1.195], ynew[2] = [0.3433653] 
Xnew[3] = [1 3 1 2200 7158 4 5 1 1 1 5 1 831 1.0], ynew[3] = [0.3433653] 
Xnew[4] = [1 3 2 1170 5387 1 5 1 2 2 2 1 1383 1.3], ynew[4] = [0.3433653] 


In [160]:
ynew1

array([[0.3433653],
       [0.3433653],
       [0.3433653],
       [0.3433653],
       [0.3433653]], dtype=float32)

In [161]:
ynew3 = model3.predict(Xnew)

In [162]:
print("The values of Xnew and its predicted yhat")
for loop in range(len(Xnew)):
        print("Xnew[%s] = %s, ynew[%s] = %s " % (loop,Xnew[loop],loop,ynew3[loop]))

The values of Xnew and its predicted yhat
Xnew[0] = [1 2 1 825 4096 1 3 3 4 4 2 2 702 0.5984251968503937], ynew[0] = [0.31589693] 
Xnew[1] = [2 1 2 600 3894 1 2 1 4 4 3 2 994 1.133], ynew[1] = [0.31589693] 
Xnew[2] = [1 3 1 1300 4796 1 5 1 1 1 4 1 1041 1.195], ynew[2] = [0.31589693] 
Xnew[3] = [1 3 1 2200 7158 4 5 1 1 1 5 1 831 1.0], ynew[3] = [0.31589693] 
Xnew[4] = [1 3 2 1170 5387 1 5 1 2 2 2 1 1383 1.3], ynew[4] = [0.3158969] 


In [163]:
ynew3

array([[0.31589693],
       [0.31589693],
       [0.31589693],
       [0.31589693],
       [0.3158969 ]], dtype=float32)